// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"メイン画面へ進む前に、\"Made with MV\"のスプラッシュ画面もしくはカスタマイズされたスプラッシュ画面を表示します。","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"OnlineAvatar","status":true,"description":"Firebaseを使ってプレイヤーをオンライン同期します。","parameters":{"apiKey":"AIzaSyBUuzm65nCCHaSXWCxfYJVgjP6Omy98gOg","authDomain":"just-experience-348619.firebaseapp.com","databaseURL":"https://just-experience-348619-default-rtdb.firebaseio.com","avatarEvent":"1","syncSwitchStart":"1","syncSwitchEnd":"60","syncVariableStart":"1","syncVariableEnd":"60"}},
{"name":"BarrierState","status":true,"description":"ステート拡張用プラグインです。詳しくはヘルプをどうぞ。","parameters":{}},
{"name":"AltMenuScreen","status":true,"description":"メニュー画面のレイアウトを変更します。","parameters":{}},
{"name":"AltSaveScreen","status":true,"description":"セーブ／ロード画面のレイアウトを変更します。","parameters":{}},
{"name":"AltWindowFrame","status":true,"description":"ウィンドウのフレームを変更します。","parameters":{}},
{"name":"HIME_WindowBackgroundColors","status":true,"description":"v1.0 ゲーム中にウィンドウ背景色と不透明度を変更できます","parameters":{"Opacity":"255","Background Color":"[0, 0, 0]"}},
{"name":"DarkPlasma_AltWindowFramePatch","status":true,"description":"AltWindowFrameのパッチプラグイン","parameters":{"Default Windowskin":"0","Custom Windowskins By Window":"[]","Custom Windowskins By Scene":"[]"}},
{"name":"CustomizeConfigDefault","status":true,"description":"オプションデフォルト値設定プラグイン","parameters":{"常時ダッシュ":"OFF","コマンド記憶":"OFF","BGM音量":"40","BGS音量":"40","ME音量":"40","SE音量":"40","常時ダッシュ消去":"OFF","コマンド記憶消去":"OFF","BGM音量消去":"OFF","BGS音量消去":"OFF","ME音量消去":"OFF","SE音量消去":"OFF"}},
{"name":"TYA_SymbolEncount","status":true,"description":"シンボルエンカウント作成の補助を行います。\r\n詳しい使い方はヘルプを参照してください。","parameters":{"situationVariables":"1"}},
{"name":"Yami_SkipTitle","status":true,"description":"テストプレイ用にタイトルシーンを飛ばすことができます。","parameters":{}},
{"name":"DimensionBox","status":true,"description":"ver1.00　ﾎﾞｯｸｽ!","parameters":{"amount":"0"}}
];
